version: '3.4'

services:
  learning.api:
    image: learningapi:dev
    container_name: Learning.API
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "Learning.API"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_learning.api$
    volumes:
      - C:\Users\Mirages1\Desktop\LaunchPad\DadJokes API Test Project\Project\Learning\Learning.API:/app
      - C:\Users\Mirages1\Desktop\LaunchPad\DadJokes API Test Project\Project\Learning:/src
      - C:\Users\Mirages1\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_learning.api$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_learning.api$ \"/app/bin/Debug/net5.0/Learning.API.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true